# Generated by Django 4.2 on 2023-05-12 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='text1',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='text1eng',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='text1ru',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='text1turk',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
