# Generated by Django 4.2 on 2023-05-12 10:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mahsulot_text1_mahsulot_text1eng_mahsulot_text1ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nomru', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nomeng', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nomturk', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('text1ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('text1eng', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('text1turk', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('ul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ul')),
            ],
        ),
    ]
