# Generated by Django 4.2 on 2023-05-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ul_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='ul',
            name='submenyu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.submenyu'),
        ),
    ]
