# Generated by Django 4.2 on 2023-05-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ul_submenyu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='title',
            new_name='title1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='titleeng',
            new_name='title2',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='titleeturk',
            new_name='title3',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='titleru',
            new_name='titleeng1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='titleeng2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titleeng3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titleeturk1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titleeturk2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titleeturk3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titleru1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titleru2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titleru3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
